# Generated by Django 6.0.4 on 2026-04-14 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=20, verbose_name='校区')),
                ('name', models.CharField(max_length=50, verbose_name='教室名称')),
                ('available_time', models.JSONField(default=list, verbose_name='可用时间段')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('college', models.CharField(blank=True, max_length=100, verbose_name='所属学院')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外院')),
                ('title', models.CharField(max_length=20, verbose_name='职称')),
                ('available_time', models.JSONField(default=list, verbose_name='不可用时间')),
                ('campus_preference', models.CharField(blank=True, max_length=20, verbose_name='校区偏好')),
                ('forbidden_with', models.ManyToManyField(blank=True, to='api.teacher', verbose_name='不宜同组名单')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('type', models.CharField(choices=[('academic', '学硕'), ('professional', '专硕')], max_length=20, verbose_name='学生类型')),
                ('campus', models.CharField(max_length=20, verbose_name='所属校区')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_students', to='api.teacher', verbose_name='对应秘书')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.teacher', verbose_name='导师')),
            ],
        ),
    ]
