# Generated by Django 6.0.4 on 2026-04-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('defense_type', models.CharField(choices=[('pre', '预答辩'), ('formal', '正式答辩'), ('mid', '中期答辩')], max_length=10, verbose_name='答辩类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前生效')),
                ('rules_snapshot', models.JSONField(default=dict, verbose_name='规则快照')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20, verbose_name='组编号')),
                ('time', models.CharField(max_length=50, verbose_name='时间段')),
                ('campus', models.CharField(max_length=20, verbose_name='校区')),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair_groups', to='api.teacher', verbose_name='主席/组长')),
                ('experts', models.ManyToManyField(related_name='expert_groups', to='api.teacher', verbose_name='专家列表')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room', verbose_name='教室')),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_groups', to='api.teacher', verbose_name='秘书')),
                ('students', models.ManyToManyField(related_name='groups', to='api.student', verbose_name='学生列表')),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.scheduleversion')),
            ],
        ),
    ]
