# Generated by Django 6.0.4 on 2026-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scheduleversion_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='forbidden_with',
        ),
        migrations.AddField(
            model_name='room',
            name='available_times',
            field=models.TextField(blank=True, verbose_name='可用时间段'),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=30, verbose_name='容纳人数'),
        ),
        migrations.AddField(
            model_name='room',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='student',
            name='defense_types',
            field=models.JSONField(default=list, verbose_name='参加答辩类型'),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='导师姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='student',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='对应秘书姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(default='学硕', max_length=20, verbose_name='学生类型'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='available_types',
            field=models.JSONField(default=list, verbose_name='可参加答辩类型'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avoid_teacher_names',
            field=models.TextField(blank=True, verbose_name='不宜同组名单'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='roles',
            field=models.JSONField(default=list, verbose_name='可担任角色'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unavailable_times',
            field=models.TextField(blank=True, verbose_name='不可用时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='campus',
            field=models.CharField(default='创新港', max_length=20, verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='教室名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(default='创新港', max_length=20, verbose_name='所属校区'),
        ),
    ]
