# Generated by Django 6.0.4 on 2026-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_available_time_remove_student_secretary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='操作类型')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('description', models.TextField(verbose_name='描述')),
                ('operator', models.CharField(default='系统', max_length=50, verbose_name='操作人')),
                ('result', models.CharField(default='成功', max_length=10, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_type', models.CharField(max_length=10, unique=True, verbose_name='答辩类型')),
                ('config', models.JSONField(default=dict, verbose_name='配置内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
