# Generated by Django 6.0.4 on 2026-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_operationlog_ruleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='conflicts_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='生成时冲突快照'),
        ),
    ]
