# Generated by Django 6.0.4 on 2026-07-03 15:35

from django.db import migrations, models
from django.db.models import Count


def _duplicate_values(model, fields):
    return list(
        model.objects.values(*fields)
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .order_by(*fields)
    )


def _format_duplicate_rows(rows, fields):
    values = []
    for row in rows:
        label = ' / '.join(str(row[field]) for field in fields)
        values.append(f'{label}({row["count"]}条)')
    return '、'.join(values)


def ensure_no_duplicate_base_data(apps, schema_editor):
    teacher = apps.get_model('api', 'Teacher')
    student = apps.get_model('api', 'Student')
    room = apps.get_model('api', 'Room')

    messages = []
    duplicate_teachers = _duplicate_values(teacher, ['name'])
    if duplicate_teachers:
        messages.append(f'教师姓名重复：{_format_duplicate_rows(duplicate_teachers, ["name"])}')

    duplicate_students = _duplicate_values(student, ['name'])
    if duplicate_students:
        messages.append(f'学生姓名重复：{_format_duplicate_rows(duplicate_students, ["name"])}')

    duplicate_rooms = _duplicate_values(room, ['campus', 'name'])
    if duplicate_rooms:
        messages.append(f'同一校区教室重复：{_format_duplicate_rows(duplicate_rooms, ["campus", "name"])}')

    if messages:
        raise ValueError('无法添加基础数据唯一约束，请先清理重复数据：' + '；'.join(messages))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scheduleversion_conflicts_snapshot'),
    ]

    operations = [
        migrations.RunPython(ensure_no_duplicate_base_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='姓名'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('campus', 'name'), name='unique_room_campus_name'),
        ),
    ]
