# Generated by Django 6.0.4 on 2026-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_base_data_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
    ]
