# Generated by Django 6.0.4 on 2026-09-15 14:47

from django.db import migrations, models


def prepare_constraints(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model('api', 'ScheduleWriteLock').objects.using(alias).get_or_create(pk=1)
    Version = apps.get_model('api', 'ScheduleVersion')
    for kind in Version.objects.using(alias).values_list('defense_type', flat=True).distinct():
        versions = list(Version.objects.using(alias).filter(defense_type=kind).order_by('created_at', 'id'))
        current = next((v.pk for v in reversed(versions) if v.is_current), None)
        used = set()
        next_number = max((v.version for v in versions), default=0) + 1
        for version in versions:
            if version.version in used:
                version.version = next_number
                next_number += 1
            used.add(version.version)
            version.is_current = version.pk == current
            version.save(using=alias, update_fields=['version', 'is_current'])
            if not version.is_current:
                def fields(obj):
                    return {f.name: getattr(obj, f.name) for f in obj._meta.fields} if obj else None
                titles = dict(apps.get_model('api', 'Teacher').objects.using(alias).values_list('name', 'title'))
                version.export_snapshot = [dict(id=g.id, group_id=g.group_id, time=g.time, campus=g.campus,
                    room=fields(g.room), chair=fields(g.chair), secretary=fields(g.secretary),
                    experts=[fields(t) for t in g.experts.all()],
                    students=[{**fields(s), 'mentor_title': titles.get(s.mentor_name, '')} for s in g.students.all()])
                    for g in version.groups.select_related('room', 'chair', 'secretary').prefetch_related('experts', 'students')]
                version.save(using=alias, update_fields=['export_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_gender_student_student_no_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWriteLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='operationlog',
            name='authoritative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='export_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='input_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='request_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='result_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=12),
        ),
        migrations.RunPython(prepare_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(fields=('defense_type', 'version'), name='unique_schedule_version'),
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('defense_type',), name='unique_current_schedule'),
        ),
    ]
