"""Run against scripts/ui-fixture-server.py on localhost:8769 after npm run build."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE = 'http://127.0.0.1:8769'
OUT = Path(__file__).resolve().parents[1] / '.tmp'
OUT.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 1050})
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(BASE + '/login')
    page.get_by_placeholder('请输入账号').fill('ui-reviewer')
    page.get_by_placeholder('请输入密码').fill('Ui-Review-Only-4926')
    page.get_by_role('button', name='登录', exact=True).click()
    page.wait_for_url('**/dashboard')
    page.wait_for_load_state('networkidle')
    page.get_by_role('button', name='开始一次答辩安排').click()
    page.wait_for_load_state('networkidle')
    expect(page.get_by_role('heading', name='先选本次答辩类型')).to_be_visible()
    page.screenshot(path=str(OUT / 'wizard-step1.png'), full_page=True)
    page.locator('.defense-choice').filter(has_text='中期答辩').click()
    page.get_by_role('button', name='下一步：准备资料').click()
    expect(page.get_by_role('button', name='资料已核对，确认要求')).to_be_enabled()
    expect(page.locator('.wizard-context')).to_contain_text('中期答辩')
    page.get_by_role('button', name='导入学生', exact=True).click()
    expect(page.get_by_role('dialog', name='导入学生名单')).to_be_visible()
    page.get_by_role('dialog', name='导入学生名单').get_by_role('button', name='取消').click()
    page.locator('.wizard-material').filter(has_text='学生名单').get_by_role('link').click()
    expect(page.locator('.wizard-return')).to_contain_text('中期答辩')
    page.get_by_role('link', name='资料已补充，返回向导').click()
    expect(page.get_by_role('heading', name='准备好学生、教师和教室')).to_be_visible()
    page.get_by_role('button', name='资料已核对，确认要求').click()
    expect(page.get_by_role('heading', name='确认日期和每组人数')).to_be_visible()
    form = page.locator('.rule-config-form')
    target = form.locator('.el-form-item').filter(has_text='每组学生人数').get_by_role('spinbutton')
    target.fill('2')
    page.get_by_role('button', name='保存要求，去生成草稿').click()
    expect(page.locator('.wizard-attention')).to_contain_text('每组学生人数需在')
    # Going back must preserve the values entered, rather than replacing them with saved defaults.
    page.get_by_role('button', name='上一步').click()
    page.get_by_role('button', name='资料已核对，确认要求').click()
    expect(target).to_have_value('2')
    page.get_by_role('link', name='返回工作台', exact=True).click()
    expect(page.get_by_text('尚有未保存的要求', exact=True)).to_be_visible()
    page.get_by_role('button', name='继续填写', exact=True).click()
    expect(target).to_have_value('2')
    page.locator('.advanced-rules summary').click()
    form.locator('.el-form-item').filter(has_text='学生最少人数').get_by_role('spinbutton').fill('1')
    page.locator('.advanced-rules summary').click()
    page.route('**/api/rule-config/**', lambda route: route.fulfill(status=503, json={'success': False, 'message': '测试保存失败'}) if route.request.method == 'POST' else route.continue_())
    page.get_by_role('button', name='保存要求，去生成草稿').click()
    expect(page.locator('.wizard-attention')).to_contain_text('测试保存失败')
    expect(target).to_have_value('2')
    page.unroute('**/api/rule-config/**')
    page.get_by_role('button', name='保存要求，去生成草稿').click()
    expect(page.get_by_role('heading', name='生成草稿，核对分组安排')).to_be_visible()
    expect(page.get_by_role('button', name='已核对，去发布与导出')).to_be_disabled()
    page.get_by_role('button', name='生成排期草稿', exact=True).click()
    preview = page.get_by_role('dialog', name='生成前，确认这次安排')
    expect(preview).to_contain_text('学生 2 人')
    expect(preview).to_contain_text('中期答辩')
    preview.get_by_role('button', name='确认生成草稿').click()
    expect(page.locator('.agenda-group')).to_have_count(1, timeout=60000)
    expect(page.get_by_role('button', name='已核对，去发布与导出')).to_be_enabled()
    expect(page.get_by_role('button', name='校验并发布')).to_have_count(0)
    page.locator('.agenda-members summary').click()
    expect(page.locator('.agenda-members')).to_contain_text('测试学生1')
    for mode in ['卡片视图', '表格视图', '日程视图']:
        page.locator('.el-radio-button').filter(has_text=mode).click()
    page.locator('.schedule-filters .el-select').nth(1).click()
    page.get_by_role('option', name='兴庆', exact=True).click()
    expect(page.get_by_role('button', name='查看全部分组')).to_be_visible()
    page.get_by_role('button', name='查看全部分组').click()
    expect(page.locator('.agenda-group')).to_have_count(1)
    page.locator('.schedule-filters .el-checkbox').click()
    expect(page.get_by_role('button', name='查看全部分组')).to_be_visible()
    page.get_by_role('button', name='查看全部分组').click()
    page.get_by_role('button', name='调整本组').click()
    page.locator('.el-drawer').get_by_role('button', name='保存', exact=True).click()
    expect(page.locator('.el-drawer')).not_to_be_visible()
    expect(page.get_by_role('button', name='已核对，去发布与导出')).to_be_enabled()
    page.screenshot(path=str(OUT / 'wizard-agenda.png'), full_page=True)
    page.get_by_role('button', name='已核对，去发布与导出').click()
    page.get_by_role('button', name='校验并发布', exact=True).click()
    expect(page.locator('.wizard-finish-note')).to_contain_text('已发布，可以下载安排表了')
    for word in (True, False):
        page.get_by_role('button', name='导出 Word/Excel').click()
        dialog = page.get_by_role('dialog', name='导出确认')
        dialog.locator('.el-radio').filter(has_text='Word 时间安排表' if word else 'Excel 分组明细').click()
        with page.expect_download() as download:
            dialog.get_by_role('button', name='继续导出').click()
        assert download.value.failure() is None
    page.reload()
    expect(page.locator('.wizard-finish-note')).to_contain_text('已发布，可以下载安排表了')
    page.get_by_role('button', name='返回工作台', exact=True).click()
    page.get_by_role('button', name='开始一次答辩安排').click()
    page.set_viewport_size({'width': 390, 'height': 844})
    page.screenshot(path=str(OUT / 'wizard-mobile.png'), full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.set_viewport_size({'width': 1440, 'height': 1050})
    page.get_by_role('button', name='下一步：准备资料').click()
    page.route('**/api/students/**', lambda route: route.fulfill(json={'success': True, 'data': []}))
    page.get_by_role('button', name='重新检查资料').click()
    expect(page.get_by_text('还需补充：学生名单', exact=True)).to_be_visible()
    expect(page.get_by_role('button', name='资料已核对，确认要求')).to_be_disabled()
    page.unroute('**/api/students/**')
    page.route('**/api/students/**', lambda route: route.fulfill(status=503, json={'success': False, 'message': '测试资料读取失败'}))
    page.get_by_role('button', name='重新检查资料').click()
    expect(page.get_by_text('测试资料读取失败', exact=True)).to_be_visible()
    expect(page.get_by_role('button', name='资料已核对，确认要求')).to_be_disabled()
    page.unroute('**/api/students/**')
    page.goto(BASE + '/schedule-wizard?step=bad&type=预答辩')
    expect(page.get_by_role('heading', name='先选本次答辩类型')).to_be_visible()
    page.get_by_role('button', name='退出登录').click()
    page.wait_for_url('**/login')
    page.get_by_placeholder('请输入账号').fill('ui-reader')
    page.get_by_placeholder('请输入密码').fill('Ui-Review-Only-4926')
    page.get_by_role('button', name='登录', exact=True).click()
    page.wait_for_url('**/dashboard')
    expect(page.get_by_role('button', name='开始一次答辩安排')).to_have_count(0)
    page.goto(BASE + '/schedule-wizard?step=3')
    expect(page.get_by_text('当前账号可查看和导出安排；创建安排需要管理员操作。', exact=True)).to_be_visible()
    expect(page.get_by_role('button', name='保存要求，去生成草稿')).to_have_count(0)
    assert not errors, errors
    print('PASS: all five wizard steps; type persistence; preparation round trip; import entry; validation; back-navigation and unsaved changes; save failure recovery; agenda filters/three views; adjustment; publish; Word+Excel downloads; refresh; empty/error/readonly/mobile; zero page errors.', flush=True)
    browser.close()
